# 15M | max_tokens=200, temperature=1, top_k=10
results_15M = [
  '. night, Tom gave his mom a big hug. She hugs him and kisses him tight. Tom tells the hug and ball. Mom helps him get in bed. Tom runs with Mom and hugs the ball tight. This is too fast and loud. He hugs every night before. He loves that box doggy with him. Heila feels happy and safe in his bed.One night, Tom noticed a small creature. It is dusty and brown. It is a furry creature. It is a bear. The tiger has a cage. Tom is scared of the animal. It bored and wants to eat Tom. He wants to say, Please, do not look in you, rat Tom says softly. He hears Moms voice. He is quiet. He tries to sleep. He opens his mouth and rubs a does not wake up. He turns around. His head is weak. He is bored.Mom comes to his room. She sees the doctor. She opening Toms hand. She gets out his ear to Tommy. She is in the living room. She says, Tommy, wake up. You are disturbing him. The bear is not a toy. It is brown and brown and white. You uncomfortable. Can you light him sleep me listened to meTom nods and says, Okay, mom. I dont want to lose our home and find out. You did not know his bed. We just need to be quiet.', 
  'leg, tight feathers said. His moms mom always told him to grown him before she pulled him to the doctor. One day, anman came to Mrs. He had an idea.Lets make corn, Mrs. The hunter said. We can fill it with grass and trees and vegetables. Then they work to make a clean fence with the plants and leaves.Mrs. Brownie was excited. He looked around and saw some boxes and some cups of corn. He asked him how to put on the corn and clean the corn in his field. Mrs Brownie beamed with pride.Mrs Brownie smiled, and ran to get his corn. On the way he saw a baby bird and he got very envious. Mrs. Brownie was afraid but remembered what Mrs Brown said. They opened the painting and made a neat lemonade for the bird. The birdie was so excited to use the corn. Mrs Brownie showed his friend the corn and helped him clean the garden with the farmer.The farmerie said, Thank you for helping me, Mr. Brownie. You also showed me how to trust when he gets some corn. They are so clean a', 
  '. I am going to a party. I have a birthday party. It is orange and blue. I can make a new cake and yummy cakeHappy birthday party. Please, for us.S island the island is blue and peaceful. No one wants to be friends with them. They hope. They wish they can have a birthday party.One day, a big wind blew. He sees a fire near the sea. It gets heading to Lizz. It sees their castle. It is very light. It rolls in the wind.Oh no says both the fire. Oh no, what is thatI told you a behave. That is a good helper. You are very pretty and strong. You are nice.The fire is still nice. It makes the room break and become very happy. It has lights and balloons.Thank you for being me, the fireman says. You are a good friend,The fireman smiles. Youre welcome, cake. But it is also yummy. Its always better than the fire. There are cookies and nuts here.Sara and the fireman thank them. They hug and go to the party. They are very good friends. They love Grand', 
  '. day, a little girl named Lily went to the park. She liked to play on the swings and the slide. She had a lot of fun.But then, she saw a big dog. The dog was barking and running towards her. Lily felt scared and ran to her mom.Mom said, Dont be scared, Lily. The dog is just a toy. He wont hurt you.Lily felt better and hugged her mom. She said, Thank you, Mom. You are a good friend.Mom smiled and said, Youre welcome, Lily. You are a good friend. Im glad you like your mom.Lily felt better and hugged her mom. She said, I love you, Mom.',
  '. day, a little girl named Lily wanted to go for a walk. She asked her mom if she could go to the park. Her mom said, Yes, but first we have to go to the park. It will be fun.Lily was very excited and ran to the park. She saw a big slide and wanted to go down it. She asked her mom if she could go up the slide. Her mom said yes, and Lily climbed up the slide.Lily was so happy and started to slide. She went up the slide and felt happy. She wanted to be like the slide too. When she got home, she sat down and started to slide down. She felt so happy.As she got to the bottom, she saw her friend Tom. She was also very good at sliding. She wanted to slide too. Lily was very good at sliding down. She slid down the slide and slid down the slide. She had so much fun and forgot all about the slide',
  'One day lily was hiding in her couch. She looked everywhere and all around but she couldnt find anyone. Just then she heard a noise. It was black and running around her box. She shouted Who lives here A voice said I have been hiding under your bedLily was scared and her eyes widened. Where are you it asked.Its your baby, she replied. Im so scared that I was hiding under my bedThe voice belonged to a small one under her bed, content to her. Lily was there to still on the couch, feeling relieved and relieved again. She put her toy down and everyone rushed back to her room playing with another toy. Alice felt safe and happy. She went to bed and dreamt of adventure with her family again.',
  'Elon the boy loved to play with his toys in his room. He had cars, dolls and books. He liked to share them with his friends, but he always wanted more.One day, he saw a big red car on the shelf. It was red and shiny. He wanted to go on it, but he did not know how to go. He asked his mom for the car to push him to the top of the hill.Sure, I will try to reverse your car, he said. He pushed his bike up the stairs and started the car. He pushed and pushed and the car moved. He felt happy.But then, a big car came out. It had a loud engine that made a loud noise. It was the cars car. It was going too fast and fast. It hit a lamp. It was a car. The car hit the lamp. It was broken.Freddy felt sad. He could not move his car. He liked it.'
]

# 1M | max_tokens=200, temperature=1, top_k=10
results_1M = [
 '. was a little boy who loved to eat lunch. His mom gave him a bowl of cheese and some cheese. The cheese was very tasty and ate. The little boy loved to play with his cheese and share the cheese with his family. The little boy ate his cheese with his mouth and he loved the cheese.One day, the little boy went to a new place to play with his cheese. The big dog liked to play with his food. He saw a big dog with a bone and a black bear. The little boy and the dog played with the cheese all day. The little boy was very happy and happy.',
 'Elon loved to i, and he loved to fly in the morning. It was a beautiful, and a big smile on a sunny day, andy was excited because he would try new things.One day, Susie decided to fly high in the sky with all day. As they flew up the clouds he could as he landed. But the sun was dark, and the sky began to fall off. Susie and Bessie tried to go, but it was too high in the sky.Then one day, Susie decided to fly to the clouds. She asked her mom if he could soar high in the sky and the clouds started to soar. The wind blew out of the wind and down, and it landed in her windowSusie couldnt believe he had been able to see the birds flying around him again. But one day, a big bird flew away. Susie was so happy to see the birds fly flying high up and higher until sh',
 'One day lily and her mom took her to the park. They liked the swings, the swings, swing and the sandbox. But one day, they saw a big dog on the swings. The dog was very big, brown. Lily wanted to play in the park but she ran back to him, but the dog was too close. He ran around the park, but he was not afraid. Lily and her mom walked away, but their mom did not. She was not happy. They ran to the big dog and saw their mom. They wanted to play on the swings in the park, but they could not find the dog. They looked sad and worried. They looked at each other. Then, they saw a big tree with lots of branches on the ground. Lily and her mom said, Lily, can we get the fence. We dont know if we do it.Mom said, Yes, but only if we do something else. You can play too',
 'One day lilyie and her friends were very excited to go to the park one day. One day, they went outside to pick swings and they went with each other. The park was starting to rain outside, but Lily was a funny frog playing them. Suddenly, Lola and there was a dog barking loudly and barking. Suddenly, the dog stopped and made him happy. Lily and her friends were very happy and started to play and teasing it. Suddenly, a friendly voice started to run around the pond and animals were laughing. The ball was so surprised to have seen the ball all the other animals with such a squirrel. It was jumping and cheering They barked it and waved goodbye. But, the dog was too cold and wide. The dog barked and scratched as he hid safely as the ball started to slip. Lily felt so sad and sad. After a while, they found that it was still so cold and rough.'
]